- RFEM/LoadCasesAndCombinations/designSituation.py
- UnitTests/test_DesignSituations.py
The Design Situation Types were originally coded exclusively for DIN National Annex. Under circumstances where the CEN remains as the National Annex, the keys for the respective design situations change. As such, the DocStrings has been updated to accomodate both CEN and DIN.
Additional regions and keys can be implemented in a similar manner.
> Design Situations Development - DocStrings Update for CEN and DIN National Annex

- RFEM/initModel.py
- UnitTests/test_initModel.py
simplified method insertSpaces
> add test for initModel insertSpaces

- RFEM/SpecialObjects/resultSection.py
- UnitTests/test_SpecialObjects.py
fixing assigned_to_surfaces and assigned_to_solids asserts
> Result Section assert fixed

- RFEM/Loads/memberLoad.py
In all cases, for all staticmethods, except on case for `MemberLoad.Force`:
```python
if load_distribution.name == "LOAD_DISTRIBUTION_UNIFORM" or load_distribution.name == "LOAD_DISTRIBUTION_UNIFORM_TOTAL":
clientObject.magnitude = load_parameter
```
_load_parameter_ is a _float_, not a _list_.
**Is now**
Right now for **analogical** case for Force and Moment user need to use float and list:
```python
MemberLoad.Force(1, 1, "1", MemberLoadDistribution.LOAD_DISTRIBUTION_UNIFORM, MemberLoadDirection.LOAD_DIRECTION_GLOBAL_Z_OR_USER_DEFINED_W_TRUE, 1000.0)
MemberLoad.Moment(2, 1, "1", MemberLoadDistribution.LOAD_DISTRIBUTION_UNIFORM, MemberLoadDirection.LOAD_DIRECTION_GLOBAL_Z_OR_USER_DEFINED_W_TRUE, [1000.0])
```
+
There is a mix between type hints, doc strings and code
**After changes**
In …
> change: load_parameter allways a list

- MANIFEST.in
We have some missing static files in our packaging process, which is stated in this issue: https://github.com/Dlubal-Software/RFEM_Python_Client/issues/163
MANIFEST.in file has been added to include these files in our package. 
Not tested yet. Should be tested in our next release.
> created MANIFEST.in

- RFEM/TypesForMembers/memberHinge.py
Bellows code 
``` python
MemberHinge(1, "Local", "", inf, inf, inf, inf, inf, inf)
MemberHinge(2, "Local", "", 1000, 2000.0, 3000, 3000, 4000, 5000)
```
Creates hinge params
So passed values are in [N] not in [kN]
> change: MemberHinge comments for units for passed values

- RFEM/TypesForMembers/memberHinge.py
Row entry for rotations contains **rotation** and **moment** not **displacement** and **force** as right now in python Client.
**Model WS definition - should be**
**python client - is now**
```python
for i,j in enumerate(rotational_release_mz_nonlinearity[1][2]):
mlvlp = Model.clientModel.factory.create('ns0:member_hinge_diagram_around_z_table_row')
mlvlp.no = i+1
mlvlp.row.displacement = rotational_release_mz_nonlinearity[1][2][i][0]
mlvlp.row.force = rotational_release_mz_nonlinearity[1][2][i][1]
mlvlp.row.spring = rotational_release_mz_nonlinearity[1][2][i][2]
mlvlp.row.note = None
clientObject.diagram_around_z_table.member_hinge_diagram_around_z_table.append(mlvlp)
```
> fix: rows entry for moments

- setup.py
In case when User want to install package from source it is not possible on Windows.
The reason is default Windows encoding https://en.wikipedia.org/wiki/Windows-1252
**To reproduce:**
```bash
git clone https://github.com/Dlubal-Software/RFEM_Python_Client.git
cd RFEM_Python_Client
python .\setup.py install
```
**Output:**
``` bash
> python .\setup.py install
Traceback (most recent call last):
File "C:\Dev\RFEM_Python_Client\setup.py", line 6, in <module>
readme = (here/"README.md").read_text()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1267, in read_text
return f.read()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
return …
```
> add: setup.py - defualt encoding to utf when reading README.md

- RFEM/TypesForMembers/memberHinge.py
User cannot create MemberHinge with nonlinearity Diagram type for my, mz. Bugs:
- object creation in wrong place (my), not happens at all (mz)
- wrong name assignment (mz)
Bellows code is executable without errors and created wished MemberHinge
```python
member_hinge_diagram_nonlinearity_1 = [MemberHingeNonlinearity.NONLINEARITY_TYPE_DIAGRAM, [MemberHingeDiagramType.DIAGRAM_ENDING_TYPE_CONTINUOUS, MemberHingeDiagramType.DIAGRAM_ENDING_TYPE_CONTINUOUS, [[0.001, 5280, None], [0.0015, 9240, None], [0.002, 12770, None], [0.0025, 15420, None], [0.003, 17450, None], [0.004, 20480, None], [0.005, 22706, None]]]]
member_hinge_diagram_nonlinearity_2 = [MemberHingeNonlinearity.NONLINEARITY_TYPE_DIAGRAM, [MemberHingeDiagramType.DIAGRAM_ENDING_TYPE_STOP, …
```
> Bug - Member hinge diagram case mz , 2 bug fixes

- RFEM/Tools/GetObjectNumbersByType.py
GetObjectNumbersByType function doesn't return correct list for E_OBJECT_TYPE_LINE_LOAD. This is because the code accesses item.no, but the Line Loads and I assume all other objects listed under Loads are accessed through item.children.
* RFEM version: 6.02.0040.48.451988f762d
* Python version: 3.11.0
> OndrejMichal: bug 40607

- RFEM/Reports/html.py
Small improvement that gives the user the choice to open the browser or not after generating the HTML report.
The default is to open the browser. This does not change the behavior of the function in existing program code.
Local test in a example.
* RFEM / RSTAB version: 6.022.0058.61
* Python version: 3.10.8
> Add a parameter for ExportResultTablesToHtml()

- RFEM/TypesForTimberDesign/timberMoistureClass.py
- RFEM/TypesForTimberDesign/timberServiceCondition.py
- RFEM/enums.py
- UnitTests/test_timberMoistureClass.py
- UnitTests/test_timberServiceCondition.py
- UnitTests/test_timberServiceConditionCSA.py
- UnitTests/test_timberServiceConditionGB.py
- UnitTests/test_timberServiceConditionNDS.py
The two functions set_timber_moisture_class and set_timber_service_conditions are implemented here. Since there are some issues with setting the right code, a thorough instruction can be found in every test file on how to test. Because of this reason the pytest.skipif function was added, so it doesn't interfere with existing tests. 
* RFEM / RSTAB version: 6.02.0060
> Knauer US-11518: Types For Timber Design - MoistureClass and ServiceCondition

- RFEM/BasicObjects/coordinateSystem.py
- RFEM/BasicObjects/coordinate_system.py
- RFEM/enums.py
- RFEM/initModel.py
- UnitTests/test_basic_objects.py
Coordinate System class and functions added. Connected to issue #275.
Coordinate System is only editable through Basic Objects so it makes sence to put it to the same folder.
* RFEM / RSTAB version: grandmaster|6.02.0073.133.ef86f73ef2b
* Python version: 3.11.3
> Coordinate System

- RFEM/dependencies.py
When I tried to run the pytest Unit tests for the first time, a lot of the tests failed because I didn't have installed _psutil_. Therefore I added it in the dependencies file.
* RFEM / RSTAB version: 6.04.0002
* Python version: 3.8.10
> added missing import to dependencies (psutil)

- RFEM/LoadCasesAndCombinations/resultCombination.py
- UnitTests/test_ResultCombination.py
I have added additional parameter for result combination items with parenthesis. Also, I added unittest for the same.
* RFEM / RSTAB version: RFEM 6.04.0002
> Heet result combination update

- Examples/CalculateInCloudExample/CalculateInCloudExample.py
- Examples/CalculateInCloudExample/README.md
- RFEM/initModel.py
I added a function to initModel.py which starts the cloud calculation for a model.
I tested the new function with the attached script test.py and two different RFEM-models, one that creates plausibility errors and one that doesn't.
[CalculateInCloudTest.zip](https://github.com/Dlubal-Software/RFEM_Python_Client/files/13476189/CalculateInCloudTest.zip)
* RFEM / RSTAB version: 6.04.0009
> Create CalculateInCloud function

- RFEM/BasicObjects/thickness.py
Added paramater **stiffness_reduction_elements_editing_enabled** for unlock user defined stiffness paramaters of thickness with layers - will be available in 6.05.0007
* RFEM / RSTAB version:
* Python version:
> added parameter for unlock stiffness modif of thickness layers

- RFEM/BasicObjects/member.py
update member.py - member defined by line for other static methods.
* RFEM / RSTAB version: RFEM 6.05.0010
> Member defined by line number

- RFEM/initModel.py
This PR solve the ``closeModel()`` issue when it is called after ``saveFile()`` with new saved model name. I also update ``openFile()`` with ``connectToServer()`` so we don't have to establish connection explicitly in script via ``Model()`` or ``connectToServer()``. 
Test script:
```py
from RFEM.initModel import Model, connectToServer, openFile, saveFile, closeModel
openFile(r'C:/Users/RojivadivaH/Desktop/Demo1.rf6')
print('Model 1 opened.')
saveFile(r'C:/Users/RojivadivaH/Desktop/new_Demo1.rf6')
print('Model 1 saved with new name.')
openFile(r'C:/Users/RojivadivaH/Desktop/Demo2.rf6')
print('Model 2 opened.')
saveFile(r'C:/Users/RojivadivaH/Desktop/new_Demo2.rf6')
print('Model 2 saved with new name.')
closeModel(2)
print('New model 2 is closed!')
closeModel(1)
print('New model 1 is …
```
> Heet update initModel

- Examples/GPT_Tank/ChatGPT_Tank_D.ipynb
- Examples/GPT_Tank/ChatGPT_Tank_E.ipynb
- Examples/GPT_Tank/RFEM_bot.py
- Examples/GPT_Tank/RFEM_prompts.py
- Examples/GPT_Tank/templates/crosssection.txt
- Examples/GPT_Tank/templates/geometry.txt
- Examples/GPT_Tank/templates/introduction.txt
- Examples/GPT_Tank/templates/load.txt
- Examples/GPT_Tank/templates/material.txt
- Examples/GPT_Tank/templates/results.txt
- Examples/GPT_Tank/templates/solver.txt
A new example which showed in the webinar about GPT integration to Webservices is created.
* RFEM version: 6.06.0011
> Webinar Example GPT_Tank

- RFEM/connectionGlobals.py
- RFEM/initModel.py
- RFEM/suds_requests.py
- UnitTests/test_DesignOverview.py
- UnitTests/test_Export.py
- UnitTests/test_GetAllObjects.py
- UnitTests/test_GlobalParameters_Test.py
- UnitTests/test_Reports.py
- UnitTests/test_ResultTables.py
- UnitTests/test_SectionDialogue.py
- UnitTests/test_nodalReleaseType.py
- UnitTests/test_suds_requests.py
- UnitTests/test_timberMoistureClass.py
- UnitTests/test_timberServiceConditionCSA.py
- UnitTests/test_timberServiceConditionGB.py
- UnitTests/test_timberServiceConditionNDS.py
Extension of Python HLF to support remote access to Webservice via network. On the server side it's necessary to run RFEM with allowed SSL connection (installed certificates) and on client side it's necessary to run RFEM Python client with proper settings in connectionGlobals.py (url to remote PC: https://x.x.x.x and api_key from Extranet/MyData). As mandatory condition it's required to have allowed remote access to Webservice for given contact which is used to login to RFEM/RSTAB on server side (it's necessary to contact Dlubal admin for that)
* RFEM version: 6.07.0001
* Python version:
> extension for remote access to Webservice via Python HLF client

- RFEM/TypesForTimberDesign/timberMoistureClass.py
- RFEM/TypesForTimberDesign/timberServiceClass.py
- RFEM/TypesForTimberDesign/timberServiceCondition.py
- UnitTests/test_timberMoistureClass.py
- UnitTests/test_timberServiceClass.py
I fixed a bug that occured while trying to create a TimberServiceClass(). There was a typo (member instead of members) in the code of the HLF.
[TimberServiceClass_Test.zip](https://github.com/user-attachments/files/16452560/TimberServiceClass_Test.zip)
* RFEM version: 6.07.0005
> Bugfix for bug 241711 (TimberServiceClass)

- RFEM/ImportExport/imports.py
For the love of god why is there sys.path.clear()??? What is going on? When ImportExport is loaded first to your program for any reason, it breaks EVERYTHING. You cannot import anything else because suddenly there is only RFEM as root... Jesus it took me so long to figure out whats going on...
If import.py is imported first, for any reason, it breaks eveything afterwards...
It hasnt because it doesnt change anything
* RFEM version:
* Python version:
> Bugfix imports.py -> remove sys.path.clear()

- Examples/SteelDesign/SteelDesignExcel.py
I fixed the example SteelDesignExcel.py again. Because of a bug in WS core the load combinations are not generated automatically which leads to an error during steel design calculation.
* RFEM version: 6.08.0007
* Python version: 3.13.0
> Temporary fix for load combinations
