- RFEM/LoadCasesAndCombinations/loadCase.py
I only changed the default value for Self Weight in class LoadCase() from 10.0 to 1.0. This is the normally used value.
> Change Default for self_weight

- README.md
Fixed image corrupted issue in [pypi](https://pypi.org/project/RFEM/) by adding image source link in README.md file.
> Heet readme update

- RFEM/LoadCasesAndCombinations/stabilityAnalysisSettings.py
- RFEM/Loads/memberLoad.py
- RFEM/TypesForSteelDesign/SteelMemberLocalSectionReduction.py
> Heet docstring update

- RFEM/Tools/GetObjectNumbersByType.py
- UnitTests/test_GetObjectNumbersByType.py
I added GetObjectNumbersByType and related unit test.
I run the unit test and its working fine.
> Matti GetObjectNumbersByType

- Examples/TankWebApp/responsiveTank.py
- RFEM/Imperfections/imperfectionCase.py
- RFEM/Tools/ModelCheck.py
- RFEM/TypesForMembers/memberEccentricity.py
- RFEM/TypesForMembers/memberNonlinearity.py
- RFEM/TypesForMembers/memberStiffnessModification.py
- RFEM/TypesForMembers/memberTransverseStiffeners.py
- RFEM/TypesForSteelDesign/steelMemberShearPanel.py
- RFEM/baseSettings.py
- RFEM/initModel.py
- UnitTests/test_LineLoads_Test.py
- UnitTests/test_MeshGenerationStatistics.py
- UnitTests/test_NodalLoad_test.py
- UnitTests/test_RigidLinks.py
- UnitTests/test_SectionDialogue.py
- UnitTests/test_SurfaceSetLoad_test.py
- UnitTests/test_TypesForNodes.py
- UnitTests/test_TypesForSurfaces.py
- UnitTests/test_basic_objects.py
- UnitTests/test_memberDefinableStiffness.py
- UnitTests/test_steelBoundaryConditions.py
- UnitTests/test_steelEffectiveLengths.py
Unusued imports were deleted using autoflake. 
Unit tests: 159 passed, 6 skipped in 190.09s (0:03:10)
* RFEM / RSTAB version: 6.02.0036.134.c884516b8f7
* Python version: 3.11.0
> Removed unused imports

- RFEM/SteelDesign/steelUltimateConfigurations.py
- UnitTests/test_steelDesignUltimateConfigurations.py
To be able to edit the steel design configurations, SteelDesign folder has created and steelDesignUltimateConfiguration class has added
* RFEM / RSTAB version: 6.02.0035
* Python version: 3.10.8
> Steel Design ULS Configurations

- RFEM/LoadCasesAndCombinations/loadCase.py
A new function to check the appropriate action categories acc. to selected national annex has added.
* RFEM / RSTAB version: 6.02.0041
* Python version: 3.10
> Action Category Check for LoadCase

- RFEM/SteelDesign/steelServiceabilityConfiguration.py
- UnitTests/test_steelBoundaryConditions.py
- UnitTests/test_steelDesignServiceabilityConfiguration.py
- UnitTests/test_steelDesignUltimateConfigurations.py
- UnitTests/test_timberDesignServiceLimitStateConfigurations.py
- UnitTests/test_timberDesignUltimateConfigurations.py
- UnitTests/test_timberMemberLocalSectionReduction.py
Added Steel Design SLS and its Unittest. 
Unittest is passed for
Version: RFEM 6.02.0044
Python: 3.11
> Heet steel design sls

- RFEM/LoadCasesAndCombinations/combinationWizard.py
- RFEM/LoadCasesAndCombinations/combinationWizards.py
- RFEM/enums.py
- UnitTests/test_combinationWizard.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* RFEM / RSTAB version:
* Python version:
> combination wizard

- RFEM/GuideObjects/note.py
- RFEM/baseData.py
- RFEM/enums.py
- UnitTests/test_baseData.py
- UnitTests/test_note.py
I have created baseDate.py, test_baseDate.py, note.py and test_note.py for:
set_model_history
set_model_parameters
set_model_parameters_location
set_model_type
set_note
* RFEM / RSTAB version: RFEM 6.02.0052
> Heet US-11521: Base Data

- RFEM/LoadCasesAndCombinations/loadCase.py
- UnitTests/test_LoadCases_Test.py
I have updated loadcase.py with available options in wsdl and added few lines in test_LoadCase_Test.py.
* RFEM / RSTAB version: RFEM 6.02.0057
> Heet load case

- Examples/Cantilever/Demo1.py
- RFEM/initModel.py
- UnitTests/test_zCalculate.py
Fixed Calculate_specific High Level Function and added unit tests which tests functionality.
#233
> Jarabroz_CalculateSpecific

- RFEM/Results/resultTables.py
Functionality update of result tables class based on issue [250](https://github.com/Dlubal-Software/RFEM_Python_Client/issues/250).
Updates:
- Default value of `object_no` attribute is set to 0.
- New attribute `include_base` is added to the static methods.
> Update Functionality of Result Tables

- RFEM/BasicObjects/line.py
- UnitTests/test_basic_objects.py
I have fixed bug in Line.NURBS and added unittest for it. Furthermore, all past unittests are working fine which include Line.NURBS.
* RFEM / RSTAB version: RFEM 6.02.0061
> Bugfix ToDo: bug 24721_Line.NURBS()

- RFEM/TypesForNodes/nodalMeshRefinement.py
- UnitTests/test_TypesForNodes.py
I fixed minor issues in NodalMeshRefinement class -missing of assigning nodes- and added unit tests. Requested from a customer.
* RFEM / RSTAB version: 6.02.0068
* Python version: 3.11.3
> BugFix: NodalMeshRefinement

- RFEM/TypesForMembers/memberEccentricity.py
fixed typo for member eccentricity TYPE_RELATIVE_AND_ABSOLUTE
> fixed typo in member eccentricity

- RFEM/SpecialObjects/surfaceRelease.py
- RFEM/TypesForSpecialObjects/surfaceReleaseType.py
- RFEM/enums.py
- UnitTests/test_SurfaceRelease.py
- UnitTests/test_SurfaceReleaseType.py
In this PR, I added surfaceRelease.py, surfaceReleaseTest.py and their Unittests.
* RFEM / RSTAB version: RFEM 6.04.0007
> Heet surface release

- UnitTests/test_DesignSituations.py
- UnitTests/test_steelEffectiveLengths.py
Update of tests which were small and created non-functional objects.
Unit tests: 223 passed, 5 skipped in 439.73s (0:07:19)
* RFEM / RSTAB version: 6.04.0009.66.6054dc8cdc
* Python version: 3.12.0
> Design Situation and Combination Wizard tests update

- RFEM/AluminumDesign/aluminumSLSConfiguration.py
- RFEM/AluminumDesign/aluminumULSConfiguration.py
- UnitTests/test_aluminumDesignSLSConfiguration.py
- UnitTests/test_aluminumDesignULSConfigurations.py
I have added aluminum design sls/uls configurations and their unittests.
* RFEM / RSTAB version: RFEM 6.04.0013
> Heet aluminum design

- RFEM/Results/resultTables.py
- UnitTests/test_resultTableAluminumDesignAddOn.py
updated resultTable.py with Aluminum Design addon results and also added Unittest for the same. 
* RFEM / RSTAB version: RFEM 6.04.0013
> Heet aluminum design result table

- Examples/CalculateInCloudExample/CalculateInCloudExample.py
- Examples/CalculateInCloudExample/README.md
I changed the example that a new model is created instead of accessing an existing model.
* RFEM / RSTAB version: 6.05.0004
> Rebecca calculate in cloud

- Examples/ConcreteBridge/concrete_bridge.py
- Examples/SteelDesign/SteelDesignExcel.py
- Examples/SteelDesign/SteelHall.py
- Examples/Timber_Design/timber_hall.py
- RFEM/Tools/PlausibilityCheck.py
- RFEM/enums.py
- RFEM/initModel.py
- UnitTests/test_plausiblityCheck.py
Updated PlausibilityCheck(), added error and warning messages. Added sys.exit() when error. PlausibilityCheck added to CalculateAll(). 
Unit tests: 228 passed, 5 skipped in 510.09s (0:08:30) latest GM
* RFEM / RSTAB version: 6.05.0006.286.2ab2d839a26
* Python version: 3.12.0
> Bugfix G-157811: WS Core - plausibility_check function returns OK even if there is problem

- RFEM/BasicObjects/coordinateSystem.py
- RFEM/BasicObjects/material.py
- RFEM/enums.py
- UnitTests/test_basic_objects.py
Added function and test for UserDefinedMaterial. Deleted redundant test of basic objects
test_basic_objects.py PASSED
* RFEM / RSTAB version: 6.05.0005.52.cd2838434c9
* Python version: 3.12.0
> Added function and test for UserDefinedMaterial

- RFEM/Results/meshTables.py
- UnitTests/test_MeshTables.py
A class for finite element mesh tables has added under results folder.
* RFEM / RSTAB version: 6.05.0007
* Python version: 3.10.8
> FE Mesh  Tables

- RFEM/BasicObjects/member.py
Updated member.py with suggested logic.
* RFEM / RSTAB version: RFEM 6.05.0010
> Update member.py 

- RFEM/Results/meshTables.py
- UnitTests/test_LineLoads_Test.py
- UnitTests/test_MeshTables.py
Updated meshTables.py with HLF for deformed FE-mesh and its unittest.  
* RFEM / RSTAB version: RFEM 6.05.0010
> Heet deformed mesh result

- RFEM/Results/resultTables.py
- UnitTests/test_ResultTables.py
Updated some important static methods in result tables to extract only unique rows which omit repeating rows of extremes and also updated unittest for the result tables.
* RFEM / RSTAB version: RFEM 6.06.0003
> Heet update result tables

- RFEM/TypesForMembers/designSupport.py
- RFEM/enums.py
- UnitTests/test_designSupport.py
Added DesignSupport.py in Types for Members to assigned design support to the members when the steel, concrete and timber design addon actived. I also added unittest for the same.
* RFEM / RSTAB version: 6.06.0005
> Heet - design support

- RFEM/ImportExport/exports.py
Typo in exports.py
* RFEM / RSTAB version: RFEM 6.06.0006
> Typo in exports.py

- RFEM/Loads/linesetLoad.py
- UnitTests/test_LineLoads_Test.py
Fixed bug LineSetLoad 
* RFEM version: 6.06.0007
> Fixed BUG : LineSetLoad

- RFEM/BasicObjects/bracing.py
- RFEM/BasicObjects/line.py
- RFEM/Loads/linesetLoad.py
- RFEM/Loads/memberLoad.py
- RFEM/Loads/membersetload.py
- RFEM/Loads/nodalLoad.py
- RFEM/Loads/openingLoad.py
- RFEM/SpecialObjects/borehole.py
- RFEM/Tools/GetObjectNumbersByType.py
- RFEM/TypesForMembers/memberHinge.py
- RFEM/TypesForMembers/memberResultIntermediatePoints.py
- RFEM/TypesForMembers/memberSpring.py
- RFEM/TypesForMembers/memberTransverseStiffeners.py
- RFEM/TypesForNodes/nodalSupport.py
- RFEM/TypesForSpecialObjects/lineReleaseType.py
- RFEM/TypesForSpecialObjects/nodalReleaseType.py
- RFEM/TypesForTimberDesign/timberServiceCondition.py
- RFEM/baseData.py
- UnitTests/test_Reports.py
- UnitTests/test_loads.py
Few enhancements regarding code style and minor bug fixes. They do not affect the tests.
Unit tests: 232 passed, 5 skipped in 574.50s (0:09:34)
* RFEM version: 6.06.0012.48.ad0ccaed1a8
* Python version: 3.12.0
> Code style fixes

- README.md
- RFEM/Results/resultTables.py
- UnitTests/test_ResultTables.py
- UnitTests/test_resultTableAddOn.py
Added HLF for timber design result table methods and updated unittest for it.
* RFEM version: 6.06.0011
> Heet timber design results

- RFEM/Results/resultTables.py
- UnitTests/test_resultTableAddOn.py
Added HLF for steel design and concrete design result tables methods and updated unitest for it.
* RFEM version: 6.06.0011
> Heet steel and concrete design result table

- RFEM/initModel.py
I fixed bug 250086. Warnings during plausibility check were not skipped if skipWarnings was set to True.
[test_Calculate_all.zip](https://github.com/user-attachments/files/16710451/test_Calculate_all.zip)
* RFEM version: 6.07.0008
> Bugfix Calculate_all

- Examples/SteelDesign/SteelDesignExcel.py
I fixed some bugs in the example that occurred due to some changes in WS Core.
* RFEM version: 6.08.0006
* Python version: 3.13.0
> Bugfix for SteelDesignExcel example
